# Generated by Django 5.1.7 on 2025-03-10 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coffee',
        ),
    ]
